version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: yudi1234
      POSTGRES_USER: postgres
      POSTGRES_DB: test
  app:
    image: dpdzero-assignment
    ports:
      - "13000:8000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
    env_file:
      - .env # Load environment variables from this file
